#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus-demo?serverTimezone=GMT
    username: root
    password: 123456
#日志配置
logging:
  level:
    com.mybatisplus: debug

